/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import event.TimeModelEvent;
import event.TimeModelListener;
import java.time.LocalDateTime;
import javax.swing.Timer;

/**
 *
 * @author acarayon
 */
public class JTimeLabel extends javax.swing.JPanel implements TimeModelListener{

    /**
     * Creates new form JTimeLabel
     */
    public JTimeLabel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("currentTime");
        add(timeLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    public void timeChanged(TimeModelEvent evt){
        String hour = Integer.toString(evt.getTime().getHour());
        String minute = Integer.toString(evt.getTime().getMinute());
        String seconde = Integer.toString(evt.getTime().getSecond());
        timeLabel.setText(hour+"h"+minute+"m"+seconde+"s");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

}
